##
## EPITECH PROJECT, 2024
## Arcade
## File description:
## Games Makefile
##

all:
	make -C ./MENU/
	make -C ./SNAKE/
	make -C ./CENTIPEDE/

clean:
	make clean -C ./MENU/
	make clean -C ./SNAKE/
	make clean -C ./CENTIPEDE/

fclean:
	make fclean -C ./MENU/
	make fclean -C ./SNAKE/
	make fclean -C ./CENTIPEDE/

re : fclean all
