##
## EPITECH PROJECT, 2024
## Arcade
## File description:
## Graphical Makefile
##

all:
	make -C ./NCURSES/
	make -C ./SDL2/
	make -C ./SFML/

clean:
	make clean -C ./NCURSES/
	make clean -C ./SDL2/
	make clean -C ./SFML/

fclean:
	make fclean -C ./NCURSES/
	make fclean -C ./SDL2/
	make fclean -C ./SFML/

re : fclean all
